// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2adHdJG9GhGxk-8rPcnX1F91McECMaEk',
    appId: '1:1024586150537:web:b23269d42e63cb629d4c58',
    messagingSenderId: '1024586150537',
    projectId: 'aquatrack-d9a72',
    authDomain: 'aquatrack-d9a72.firebaseapp.com',
    storageBucket: 'aquatrack-d9a72.firebasestorage.app',
    measurementId: 'G-M67YQJ0BVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYEJ9crLy5GoE9hnPmRbRKDWukw761NK0',
    appId: '1:1024586150537:android:1a6b04bf1157fa0c9d4c58',
    messagingSenderId: '1024586150537',
    projectId: 'aquatrack-d9a72',
    storageBucket: 'aquatrack-d9a72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzQMoMFKkDZ_93TpRzpTQQivRLm1kGFg',
    appId: '1:1024586150537:ios:a14cce2a7bdb38509d4c58',
    messagingSenderId: '1024586150537',
    projectId: 'aquatrack-d9a72',
    storageBucket: 'aquatrack-d9a72.firebasestorage.app',
    iosBundleId: 'com.example.aquatrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEzQMoMFKkDZ_93TpRzpTQQivRLm1kGFg',
    appId: '1:1024586150537:ios:a14cce2a7bdb38509d4c58',
    messagingSenderId: '1024586150537',
    projectId: 'aquatrack-d9a72',
    storageBucket: 'aquatrack-d9a72.firebasestorage.app',
    iosBundleId: 'com.example.aquatrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2adHdJG9GhGxk-8rPcnX1F91McECMaEk',
    appId: '1:1024586150537:web:22e874f36311fa5d9d4c58',
    messagingSenderId: '1024586150537',
    projectId: 'aquatrack-d9a72',
    authDomain: 'aquatrack-d9a72.firebaseapp.com',
    storageBucket: 'aquatrack-d9a72.firebasestorage.app',
    measurementId: 'G-HHTHK1TXK5',
  );
}
